# Site settings
title: Microsoft Technical Case Studies
email: dcaro@microsoft.com
# description: 
baseurl: "/test-pages-lfs" # the subpath of your site, e.g. /blog/
url: "https://www.github.io/jrebagliatti" # the base hostname & protocol for your site
encoding: utf-8
github_username:  jrebagliatti
use_static_category_list: false # true/false: use true to indicate that site will use 
                               # the static category list to build the category tree. 
                               # Use false to indicate the site to build the category 
                               # tree dynamically using the posts' metadata 
git_lfs_server_url: "https://media.githubusercontent.com/media/jrebagliatti/test-pages-lfs/master"
# Build settings
# markdown: redcarpet
# highlighter: pygments
# extensions: [tables fenced_code_blocks]

exclude: [vendor]
kramdown:
   input: GFM
gems:
  - jekyll-sitemap
